plugins {
    id 'java'
    id 'application'
}

group = 'ru.nsu'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

application {
    mainClass = 'ru.nsu.factory.FactoryApp'
}

sourceSets {
    main {
        resources {
            srcDirs = ['src/main/resources']
        }
    }
}

jar {
    manifest {
        attributes 'Main-Class': 'ru.nsu.factory.FactoryApp'
    }
    from {
        configurations.runtimeClasspath.collect {
            it.isDirectory() ? it : zipTree(it)
        }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

run {
    standardInput = System.in
    systemProperty "java.util.logging.config.file", "src/main/resources/logging.properties"
    jvmArgs "-Dsun.java2d.uiScale=2.0",
            "-Dsun.java2d.uiScale.enabled=true"
}

test {
    useJUnitPlatform()
}
